apiVersion: batch/v1
kind: Job
metadata:
  name: bigdata
spec:
  backoffLimit: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: bigdata
        run: bigdata
    spec:
      containers:
      - command: ["sh","-c"]
        args: ["cp /sparkcode/sparkTest.py /app/; python sparkTest.py"]
        image: 100.125.0.198:20202/vw-test1234/bigdataspark:latest
        imagePullPolicy: Always
        name: bigdata
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: sparkcode
            mountPath: /sparkcode
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sparkcode
        configMap:
          name: spark-code
          items:
            - key: sparkTest.py
              path: sparkTest.py
