apiVersion: batch/v1
kind: Job
metadata:
  name: bigdata
spec:
  backoffLimit: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: bigdata
        run: bigdata
    spec:
      containers:
      - command: ["sh","-c"]
        args: ["python sparkTest.py"]
        image: andperu/spark:XXX
        imagePullPolicy: Always
        name: bigdata
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30